from Validation.validate_functions import is_email_registered,is_valid_aadhar,is_valid_contact
from Validation.validate_functions import is_valid_dob,is_valid_email,is_valid_experience
from Validation.validate_functions import is_valid_password,is_valid_username
